[LibOS,PAL] Add flexible device-specific IOCTL support
The newly added `ioctl()` syscall emulation on device-backed file
descriptors is pass-through. It is insecure by itself since the
emulation only passes the arguments to and from the untrusted memory:
- IOCTL arguments are passed as-is from the app to the untrusted host,
  which may lead to leaks of secret data;
- untrusted host can change IOCTL arguments as it wishes when passing
  them from Gramine to the device and back.

It is the responsibility of the app developer to correctly use IOCTLs,
with security implications in mind. In most cases, IOCTL arguments should
be encrypted or integrity-protected with a key pre-shared between
Gramine and the device.

On the Linux-SGX PAL, a set of IOCTL requests must be explicitly allowed
in the manifest via the new option `sgx.allowed_ioctls`.
Also, the allowed IOCTLs' arguments (typically pointers to complex
nested objects) must be explicitly described in the manifest via the new
option `sgx.ioctl_structs.[identifier]` and a corresponding reference in
`sgx.allowed_ioctls`; see docs for explanation of the IOCTL struct
format.

This commit adds three new LibOS tests to verify the flexible IOCTL
logic against Gramine dummy device `/dev/gramine_test_dev`. This device
is located in companion repo `gramineproject/device-testing-tools`. One
test checks IOCTL data passing, second test checks that Gramine forbids
unknown IOCTLs, third test checks that Gramine IOCTL parser fails on
incorrect manifest formatting.

Signed-off-by: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>

diff --git a/.ci/lib/stage-build-sgx-vm.jenkinsfile b/.ci/lib/stage-build-sgx-vm.jenkinsfile
--- a/.ci/lib/stage-build-sgx-vm.jenkinsfile
+++ b/.ci/lib/stage-build-sgx-vm.jenkinsfile
@@ -9,14 +9,17 @@ stage('build') {
         cd initramfs_builder
         {
            echo '#!/bin/sh'
-           echo 'if test -n $SGX; then GRAMINE=gramine-sgx; else GRAMINE=gramine-direct; fi'
+           echo 'set -e'
            echo 'cd $PWD_FOR_VM'
            echo '( cd device-testing-tools/gramine-device-testing-module; insmod gramine-testing-dev.ko )'
 
            # only couple tests -- executing in a VM with virtio-9p-pci FS passthrough is very slow
            echo 'cd libos/test/regression'
-           echo 'gramine-test build helloworld; $GRAMINE helloworld'
-           echo 'gramine-test build device_ioctl; $GRAMINE device_ioctl'
+           echo 'gramine-test build'
+           echo 'gramine-test pytest -v -k test_001_helloworld'
+           echo 'gramine-test pytest -v -k test_003_device_ioctl'
+           echo 'gramine-test pytest -v -k test_004_device_ioctl_fail'
+           echo 'gramine-test pytest -v -k test_005_device_ioctl_parse_fail'
            echo 'echo "TESTS OK"'
            echo 'poweroff -n -f'
         } > new_init
